affiliate/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('products.urls')),
]
urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views
app_name="products"
urlpatterns = [
    path('',views.home,name='home'),
    path('product-detail/<int:id>/',views.product_details,name='product_details'),
    path('about',views.about_us,name='about'),
    path("services",views.our_services,name="services"),
    path("search",views.search,name="search"),
    path("contacts",views.contactView,name="contact"),
]

products/models.py
from django.db import models

# Create your models here.

class Product(models.Model):
    title=models.CharField(max_length=200)
    brand=models.CharField( max_length=50)
    image=models.URLField( max_length=200,null=True, blank=True)
    amazon_link=models.TextField(null=True, blank=True)
    text_link=models.URLField( max_length=300, null=True, blank=True)
    image_link1=models.TextField( null=True, blank=True)
    description=models.TextField()
    config=models.TextField( null=True, blank=True)
    price=models.DecimalField(max_digits=7, decimal_places=2, null=True, blank=True)
    discount_price=models.DecimalField(max_digits=7, decimal_places=2, null=True, blank=True)
    other_image=models.URLField(max_length=300, null=True, blank=True)
    other_image1=models.URLField(max_length=300, null=True, blank=True)


    def __str__(self):
        return self.title+' '+self.brand
    
    class Meta:
        ordering=['title','brand',]

class About_us(models.Model):
    title=models.CharField(max_length=200)
    image1=models.URLField( max_length=200 ,null=True,blank=True)
    image2=models.URLField( max_length=200 ,null=True,blank=True)
    image3=models.URLField( max_length=200 ,null=True,blank=True)
    image4=models.URLField( max_length=200 ,null=True,blank=True)
    image5=models.URLField( max_length=200 ,null=True,blank=True)
    facebook_page1=models.URLField( max_length=200 ,null=True,blank=True)
    facebook_page2=models.URLField( max_length=200 ,null=True,blank=True)
    youtube_channel=models.URLField( max_length=200 ,null=True,blank=True)
    instagram=models.URLField( max_length=200 ,null=True,blank=True)
    github=models.URLField( max_length=200 ,null=True,blank=True)
    description=models.TextField()
    
    def __str__(self):
        return self.title
    
    class Meta:
        ordering=['title',]
        verbose_name_plural="About Us"

class Service(models.Model):
    title=models.CharField(max_length=200)
    description=models.TextField()
    
    def __str__(self):
        return self.title
    
    class Meta:
        ordering=['title',]
        verbose_name_plural="Services"

class Team(models.Model):
    name=models.CharField( max_length=200)
    image=models.URLField( max_length=500,null=True,blank=True)
    position=models.CharField(max_length=50)
    description=models.TextField(("description"),null=True,blank=True)
    email=models.EmailField(("email"), max_length=254)
    date_join=models.DateTimeField(("date join"),auto_now_add=True)

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name_plural="Team"
class Messages(models.Model):
    name=models.CharField(max_length=150)
    phone_number=models.IntegerField()
    email=models.EmailField(("email"), max_length=254)
    message=models.TextField(("message"))
    send_date=models.DateTimeField(("send date"), auto_now=True)

    def __str__(self):
        return self.name
    
    class Meta:
        ordering=['name',]
        verbose_name='Message'
        verbose_name_plural="Messages"

class Contact(models.Model):
   
    image=models.URLField(("image url"), max_length=200)
    phone_number=models.IntegerField()
    email=models.EmailField(("email"), max_length=254)
    country=models.CharField(max_length=50)
    region=models.CharField(max_length=50)
    town=models.CharField(max_length=50)
    street=models.CharField(max_length=50,null=True,blank=True)
    def __str__(self):
        return self.country+' '+self.email
    
    class Meta:
        ordering=['country','phone_number',]

products/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import *
from django.views import View
from django.contrib import messages
# Create your views here.

def home(request):
    products=Product.objects.all()
    services=Service.objects.all()
    context={
        'products':products,
        'services':services,
    }
    return render(request,'home.html',context)

def product_details(request,id):
    product=get_object_or_404(Product,pk=id)
    context={
        'product':product,
    }
    print(product.title)
    return render(request,'detail.html',context)

def about_us(request):
    team=Team.objects.all()
    about=About_us.objects.get(title__icontains='Best-Products')
    services=Service.objects.all()
    context={
        "about":about,
        'members':team,
        'services':services,

    }
    return render(request,'about.html',context)

def our_services(request):
    services=Service.objects.all()
    context={
        'services':services,
    }
    return render(request,"services.html",context)

def search(request):
    n=request.GET["search"]

    return redirect(f"https://www.amazon.com/s?k={n}&tag=codermiki-20")

def contactView(request):
    if request.method=="GET":
        contact=Contact.objects.all()
        team=Team.objects.all()
        about=About_us.objects.get(title__icontains='Best-Products')
        context={
            "contact":contact,
            'members':team,
            "about":about,
        }
        return render(request,"contact.html",context)
    if request.method=="POST":
        print(request.POST)
        name=request.POST['name']
        phone=request.POST['phone']
        email=request.POST['email']
        message=request.POST['message']
        if name!='' and phone!=''and email!=''and message!='':
           msg=Messages.objects.create(name=name,phone_number=phone,email=email,message=message)
           print(" this was a good data and was save")
           messages.info(request,f"Dr  {request.user} Your Notes was Saved successfully ")
        else:
            print("his was not good data and was not save")
            messages.info(request,f"Dr  {request.user} please fill all the fields currectly before submiting the form ")
        return redirect("products:contact")

templates/about.html
{% extends 'index.html' %}
{% load static %}

{% block title %}
About US
{% endblock title %}

 {% block content %}
  <!-- Page Content -->
  <div class="container">
 <img class="img-fluid rounded-circle mb-4" src="{% static 'imgs/LOGO.pNg' %}" alt="IMAGE FAILED TO LOAD">
    <!-- Page Heading/Breadcrumbs -->
    <h1 class="mt-4 mb-3 text-center p-5">About Us</h1>

    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <a href="{% url 'products:home' %}">Home</a>
      </li>
      <li class="breadcrumb-item active">About Us</li>
    </ol>
   

    <!-- Intro Content -->
    <div class="row">
      <div class="col-lg-6">
      {% if about.image1 %}
      
       <img class="img-fluid rounded mb-4" src="{{about.image1}}" alt="Image Fail To Load">
        {% else %}
        <img class="img-fluid rounded mb-4" src="http://placehold.it/750x450" alt="Image Fail To Load">
        {% endif %}
      </div>
      <div class="col-lg-6">
        <h2>About {{about.title}}</h2> <a href="{{about.image2}}">{{about.image2}}</a>
        <p>{{about.description}}</p>
      </div>

    </div>
    <!-- /.row -->
<!-- Other images of Best-Product-->

<hr/>


<h1 class="mt-4 mb-3 text-center">Other images of Best-Product</h1>

    <div class="row">
      <div class="col-lg-4">
      {% if about.image2 %}
      
       <img class="img-fluid rounded mb-4" src="{{about.image2}}" alt="Image Fail To Load">
       
        {% endif %}
      </div>
      <div class="col-lg-4">
      {% if about.image2 %}
      
       <img class="img-fluid rounded mb-4" src="{{about.image2}}" alt="Image Fail To Load">
       
        {% endif %}
      </div>
      <div class="col-lg-4">
      {% if about.image3 %}
      
       <img class="img-fluid rounded mb-4" src="{{about.image3}}" alt="Image Fail To Load">
       
        {% endif %}
      </div>
      <div class="col-lg-4">
      {% if about.image4 %}
      
       <img class="img-fluid rounded mb-4" src="{{about.image4}}" alt="Image Fail To Load">
       
        {% endif %}
      </div>
      <div class="col-lg-4">
      {% if about.image5 %}
      
       <img class="img-fluid rounded mb-4" src="{{about.image5}}" alt="Image Fail To Load">
       
        {% endif %}
      </div>
      </div>
      
<hr/>

<h1 class="mt-4 mb-3 text-center">Our Links and Reachouts</h1>
 <div class="row  bg-secondary">
      <div class="col-lg-2">
      {% if about.facebook_page1 %}
       <a href="{{about.facebook_page1}}"><li class="  btn  btn-sm btn-primary fa  fa-facebook " ><br>facebook</li></a>
        {% endif %}
      </div>

      <div class="col-lg-3">
      {% if about.facebook_page2 %}
       <a href="{{about.facebook_page2}}"><li class=" btn  btn-sm btn-primary fa  fa-facebook " ><br>facebook</li></a>
        {% endif %}
      </div>

      <div class="col-lg-3">
      {% if about.youtube_channel %}
       <a href="{{about.youtube_channel}}"><li class="btn btn-sm  btn-danger fa  fa-youtube-play  " ><br>Youtube</li></a>
        {% endif %}
      </div>

      <div class="col-lg-2">
      {% if about.instagram  %}
       <a href="{{about.instagram }}"><li class="btn btn-sm  btn-danger fa  fa-instagram  " ><br>Instgram</li></a>
        {% endif %}
      </div>

       <div class="col-lg-2">
      {% if about.github  %}
       <a href="{{about.github }}"><li class="btn btn-sm btn-success fa  fa-github  " ><br>Github</li></a>
        {% endif %}
      </div>

</div>
<hr/>
    <!-- Team Members -->
    <h2>Our Team</h2>

    <div class="row">
    {% for member in members %}
      <div class="col-lg-4 mb-4">
        <div class="card h-100 text-center">
         {% if member.image %}
          <img class="card-img-top" src="{{member.image}}" alt="">
          {% endif %}
          <div class="card-body">
            <h4 class="card-title">{{member.name}}</h4>
            <h6 class="card-subtitle mb-2 text-muted">{{member.position}}</h6>
            <p class="card-text">{{member.description}}.</p>
          </div>
          <div class="card-footer">
            <a href="#">{{member.email}}</a>
          </div>
        </div>
      </div>
      {% endfor %}
  
    </div>
    <!-- /.row -->

    <!-- Our Customers -->
    <h2>Our Services</h2>
    <div class="row">
    {% for service in services %}
      <div class="col-lg-6 col-sm-4 mb-4">
      <strong>{{service.title|title}}</strong>
      <p>{{service.description}}</p>
      </div>
      {% endfor %}
      </div>

      
      <h2>Our Customers</h2>
      <div class="row">
      <div class="col-lg-2 col-sm-4 mb-4">
        <img class="img-fluid" src="http://placehold.it/500x300" alt="">
      </div>
      <div class="col-lg-2 col-sm-4 mb-4">
        <img class="img-fluid" src="http://placehold.it/500x300" alt="">
      </div>
      <div class="col-lg-2 col-sm-4 mb-4">
        <img class="img-fluid" src="http://placehold.it/500x300" alt="">
      </div>
      <div class="col-lg-2 col-sm-4 mb-4">
        <img class="img-fluid" src="http://placehold.it/500x300" alt="">
      </div>
      <div class="col-lg-2 col-sm-4 mb-4">
        <img class="img-fluid" src="http://placehold.it/500x300" alt="">
      </div>
    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->
 {% endblock content %}

 

templates/contact.html
{% extends 'index.html' %}
{% block title %}
contact
{% endblock title %}
 
 {% block content %}
  <!-- Page Content -->
  <div class="container">

    <!-- Page Heading/Breadcrumbs -->
    <h1 class="mt-4 mb-3">Contact
     
    </h1>
 <div class="bg-primary text-danger">
        {% for message in messages %}
          <h3 class="is_invalid">{{message}}</h3>
        {% endfor %}
    </div>
    <!-- Content Row -->
    <div class="row">
      <!-- Map Column -->
      {% for contact in contact%}
      <div class="col-lg-8 mb-4">
        <!-- Embedded Google Map -->
        <iframe width="100%" height="400px" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="{{contact.image}}"></iframe>
      </div>
      <!-- Contact Details Column -->
      <div class="col-lg-4 mb-4">
        <h3>Contact Details</h3>
        <p>Location:
          {{contact.country}}
          <br> {{contact.region}},{{contact.town}}, {{contact.street}}
          <br>
        </p>
        <p>
          <abbr title="Phone">Phone</abbr>:<a href="tel:{{contact.phone_number}}"> (+237) {{contact.phone_number}}</a>
        </p>
        <p>
          <abbr title="Email">Email</abbr>:
          <a href="mailto:name@example.com"> {{contact.email}}
          </a>
        </p>
        <p>
          <abbr title="Hours">H</abbr>: Monday - Friday: 9:00 AM to 5:00 PM
        </p>
      </div>
      {% endfor %}
    </div>
    <!-- /.row -->

    <hr/>
    <!-- Team Members -->
    <h2>Our Team</h2>

    <div class="row">
    {% for member in members %}
      <div class="col-lg-4 mb-4">
        <div class="card h-100 text-center">
         {% if member.image %}
          <img class="card-img-top" src="{{member.image}}" alt="">
          {% endif %}
          <div class="card-body">
            <h4 class="card-title">{{member.name}}</h4>
            <h6 class="card-subtitle mb-2 text-muted">{{member.position}}</h6>
            <p class="card-text">{{member.description}}.</p>
          </div>
          <div class="card-footer">
            <a href="#">{{member.email}}</a>
          </div>
        </div>
      </div>
      {% endfor %}
  
    </div>
    <!-- /.row -->

    <h1 class="mt-4 mb-3 text-center">Our Links and Reachouts</h1>
 <div class="row  bg-secondary">
      <div class="col-lg-2">
      {% if about.facebook_page1 %}
       <a href="{{about.facebook_page1}}"><li class="  btn  btn-sm btn-primary fa  fa-facebook " ><br>facebook</li></a>
        {% endif %}
      </div>

      <div class="col-lg-3">
      {% if about.facebook_page2 %}
       <a href="{{about.facebook_page2}}"><li class=" btn  btn-sm btn-primary fa  fa-facebook " ><br>facebook</li></a>
        {% endif %}
      </div>

      <div class="col-lg-3">
      {% if about.youtube_channel %}
       <a href="{{about.youtube_channel}}"><li class="btn btn-sm  btn-danger fa  fa-youtube-play  " ><br>Youtube</li></a>
        {% endif %}
      </div>

      <div class="col-lg-2">
      {% if about.instagram  %}
       <a href="{{about.instagram }}"><li class="btn btn-sm  btn-danger fa  fa-instagram  " ><br>Instgram</li></a>
        {% endif %}
      </div>

       <div class="col-lg-2">
      {% if about.github  %}
       <a href="{{about.github }}"><li class="btn btn-sm btn-success fa  fa-github  " ><br>Github</li></a>
        {% endif %}
      </div>

</div>
<hr/>

    <!-- Contact Form -->
    <!-- In order to set the email address and subject line for the contact form go to the bin/contact_me.php file. -->
    <div class="row">
      <div class="col-lg-8 mb-4">
        <h3>Send us a Message</h3>
        <form action="" method="post" name="sentMessage" id="contactForm" novalidate>
        {% csrf_token %}
          <div class="control-group form-group">
            <div class="controls">
              <label>Full Name:</label>
              <input type="text" class="form-control" id="name" name="name" required data-validation-required-message="Please enter your name.">
              <p class="help-block"></p>
            </div>
          </div>
          <div class="control-group form-group">
            <div class="controls">
              <label>Phone Number:</label>
              <input type="tel" class="form-control" id="phone" name="phone" required data-validation-required-message="Please enter your phone number.">
            </div>
          </div>
          <div class="control-group form-group">
            <div class="controls">
              <label>Email Address:</label>
              <input type="email" class="form-control" id="email" name="email" required data-validation-required-message="Please enter your email address.">
            </div>
          </div>
          <div class="control-group form-group">
            <div class="controls">
              <label>Message:</label>
              <textarea rows="10" cols="100" class="form-control" id="message" name="message" required data-validation-required-message="Please enter your message" maxlength="999" style="resize:none"></textarea>
            </div>
          </div>
          <div id="success"></div>
          <!-- For success/fail messages -->
          <button type="submit" class="btn btn-primary" id="sendMessageButton">Send Message</button>
        </form>
      </div>

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->
 {% endblock content %}

  

templates/detail.html
{% extends 'index.html' %}

{% block title %}
detail page
{% endblock title %}

{% block content %}

  <div class="container  p-5 mt-5 text-dark" > 
  <h2>{{product.title|title}}</h2>
  <h3>{{product.brand}}</h3>
  <img width="100%" src="{{product.image}}" alt="">
<hr class="bg-primary">
  <blockquote class="bg-secondary text-light">
    <h3 class=" text-center" ><u><i>Configuration:</i></u></h3>
      <pre class="bg-secondary text-light">
        {{product.config}}
      </pre>
  </blockquote >
  <hr class="bg-dark" >
  <h3 class=" text-center" ><u><i>Description:</i></u></h3>
  <div class="row">
    <div class="col-lg-8">
      <blockquote class="bg-dark text-light">
      {{product.description|safe}}
  </blockquote>
    </div>
    <div class="col-4">
      
      {% if product.other_image %}
       <img width="100%" src="{{product.other_image}}" alt="">
      {% endif %}
      {% if product.other_image1 %}
       <img width="100%" src="{{product.other_image1}}" alt="">
      {% endif %}
        
    </div>
  </div>
  <hr class="bg-primary">
<p>Price:
{% if product.discount_price %}
<del class="bg-danger">${{product.price}}</del>
<strong class="bg-success">${{product.discount_price}}</strong>
{% else %}
<strong class="bg-success">${{product.price}}</strong>
    
{% endif %}</p>
    

<p>Please click on this link <a href="{{product.text_link}}">Here</a> to buy or hit/click any of the images below to buy this product </p>

<div class="row">
    <div class="col-lg-6">
 {{product.image_link1|safe}}
</div>
 <div class="col-lg-6">
   {{product.amazon_link|safe}}
  </div>
</div>

  </div>
{% endblock content %}

templates/header.html
{% load static %}
  <header>
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>

         <li data-target="#carouselExampleIndicators" data-slide-to="3" ></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="4"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <!-- Slide One - Set the background image for this slide in the line below -->
        <div class="carousel-item active" style="background-image: url('{% static 'imgs/f.jpg' %}');background-position:center;background-repeat:no-repeat;background-size:cover">
          <div class="carousel-caption d-none d-md-block">
            <h3 class="">Best Product</h3>
            <p class="">his is are just for you,your friends and family.</p>
          </div>
        </div>
        <!-- Slide Two - Set the background image for this slide in the line below -->
        <div class="carousel-item" style="background-image: url('{% static 'imgs/s.jpg' %}');background-position:center;background-repeat:no-repeat;background-size:cover">
          <div class="carousel-caption d-none d-md-block">
            <h3 class="">Best Reviews</h3>
            <p class="">For you to make better choices from with confidence.</p>
          </div>
        </div>
        <!-- Slide Three - Set the background image for this slide in the line below -->
        <div class="carousel-item" style="background-image: url('{% static 'imgs/t.jpg' %}');background-position:center;background-repeat:no-repeat;background-size:cover">
          <div class="carousel-caption d-none d-md-block">
            <h3 class="">We Are Here For You</h3>
            <p class="">just at your service as you want us to be with best deals no mistakes</p>
          </div>
        </div>

      <!-- Slide Three - Set the background image for this slide in the line below -->
        <div class="carousel-item" style="background-image: url('{% static 'imgs/f1.jpg' %}');background-position:center;background-repeat:no-repeat;background-size:cover">
          <div class="carousel-caption d-none d-md-block">
            <h3 class="">We Are Here For You</h3>
            <p class="">just at your service as you want us to be with best deals no mistakes</p>
          </div>
        </div>

        <!-- Slide Three - Set the background image for this slide in the line below -->
        <div class="carousel-item" style="background-image: url('{% static 'imgs/s1.jpg' %}');background-position:center;background-repeat:no-repeat;background-size:cover">
          <div class="carousel-caption d-none d-md-block">
            <h3 class="">We Are Here For You</h3>
            <p class="">just at your service as you want us to be with best deals no mistakes</p>
          </div>
        </div>

        <!-- Slide Three - Set the background image for this slide in the line below -->
        <div class="carousel-item" style="background-image: url('{% static 'imgs/t1.jpg' %}');background-position:center;background-repeat:no-repeat;background-size:cover">
          <div class="carousel-caption d-none d-md-block">
            <h3 class="">We Are Here For You</h3>
            <p class="">just at your service as you want us to be with best deals no mistakes</p>
          </div>
        </div>


      </div>
      <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </header>

templates/home.html
{% extends 'index.html' %}
{% load static %}
{% block title %}
Best-Products home
{% endblock title %}





{% block content %}
{% include 'header.html' %}
  <div class="container">
    <div class=" text-center text-light p-5 bg-dark mb-2 rounded-circle" id="bg">
    <h1 class="my-3">Welcome to Best-Products</h1>


    <!-- Products Section -->
    <h2 class="text-center text-light bg-primary dark rounded-circle container">Hight Rating Products</h2>
    <p class="bg-primary">we get you close to good products ranging from electronic,educational to body ware products etc. <br>Make a good choice of product because we have a lot here for you </p>
    <h3  ><div class="text-center text-light bg-primary dark rounded-circle "> #BEST-PRODUCTS</div> .........we bring customers and products together</h3>
    </div> 
    <div class="row">
    {% for product in products %}
      <div class="col-lg-4 col-sm-6 portfolio-item">
        <div class="card h-100">
        <img  class="" src="{{product.image}}" height=250>
          {% comment %} {{product.image_link1|safe}} {% endcomment %}
          <div class="card-body">
            <h4 class="card-title">
              <a href="{{product.text_link}} " target='_blank'>{{product.title|truncatewords:5}}</a>
            </h4>
            <p class="card-text">{{product.description|truncatewords:30}}</p>
            <a class="btn-secondary" href="{% url 'products:product_details' product.id %}">Read More..</a>
              <br>
              {% if product.discount_price %}
               <a class=" btn-success col-4" href="{{product.text_link}} "><del>price: ${{product.price}}</del></a>
          <a class=" btn-primary col-7 " href="{{product.text_link}} ">discount price: ${{product.discount_price}}</a>
          {% else %}
           <a class=" btn-success col-4" href="{{product.text_link}} ">price: ${{product.price}}</a>
          {% endif %}
            
          </div>
         
        </div>
      </div>
      {% endfor %}
      
    </div>
    <!-- /.row -->
<h3 class="text-center p-5 "> 
<a target="_blank" href="https://www.amazon.com/gp/search?ie=UTF8&tag=codermiki-20&linkCode=ur2&linkId=07dde427e14ee4510a26e6a19522d2ad&camp=1789&creative=9325&index=aps&keywords=best computer best phones best books joweleries">more products</a><img src="//ir-na.amazon-adsystem.com/e/ir?t=codermiki-20&l=ur2&o=1" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />
</h3>
    <!-- Features Section -->
    <div class="row">
      <div class="col-lg-6">
        <h2>Our Services and deals</h2>
        <p>The BEST-Products Services includes:</p>
        <div class="row">
      {% for service in services %}
      <div class="col-lg-6 col-sm-4 mb-4">
      <strong>{{service.title|title}}</strong>
      <p>{{service.description}}</p>
      </div>
      {% endfor %}
      </div>
        
      </div>
      <div class="col-lg-6">
        <img class="img-fluid rounded" src="{% static 'imgs/f1.jpg' %}" alt="no image to show">
      </div>
    </div>
    <!-- /.row -->

    <hr>

  </div>

{% endblock content %}

templates/navbar.html
{% load static %}

<!-- Navigation -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-secondary fixed-top">
<div class="fixed-top">
  <form action="{% url 'products:search' %}" target="_blank" class="float-right  form-inline ml-auto">
  <input class="" type='text' placeholder="Search Products Here" name="search">
  <button class=" btn btn-sm btn-success ml-lg-2" type='submit'> Search</button>
  </form>
  </div>

    <div class="container pt-2 text-light">
    <img src="{% static 'imgs/LOGO.png' %}" width="50" alt="">
      <a class="navbar-brand text-light" style="font:1.8em castellar;" href="/">Best-Products</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto ">
         <li class="nav-item">
            <a class="nav-link text-light" href="{% url 'products:home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-light" href="{% url 'products:about' %}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-light" href="{% url 'products:services' %} ">Services</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-light" href="{% url 'products:contact' %}">Contact</a>
          </li>
         
        </ul>
      </div>
    </div>
  </nav>

templates/services.html
{% extends 'index.html' %}
{% load static %}
{% block title %}
Services
{% endblock title %}
  <!-- Page Content -->
 {% block content %}

  <div class="container">
  <div class="bg-success" style="background:url('{% static 'imgs/s.jpg' %}');background-repeat:no-repeat;background-size:cover;">
 <img class="img-fluid rounded-circle mb-4" src="{% static 'imgs/LOGO.pNg' %}" alt="IMAGE FAILED TO LOAD">
    <!-- Page Heading/Breadcrumbs -->
    <h1 class="mt-4 mb-3 text-center p-5">Our Services</h1>
</div>
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <a href="{% url 'products:home' %}">Home</a>
      </li>
      <li class="breadcrumb-item active">Our Services</li>
    </ol>


    <!-- Marketing Icons Section -->
    <div class="row">
    {% for service in services %}
      <div class="col-lg-4 mb-4">
        <div class="card h-100">
          <h4 class="card-header">{{service.title|title}}</h4>
          <div class="card-body">
            <p class="card-text">{{service.description}}....</p>
          </div>
          <div class="card-footer">
            <a href="#" class="btn btn-primary">Learn More</a>
          </div>
        </div>
      </div>
      {% endfor %}
    
    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->

 {% include 'header.html' %}

 {% endblock content %}